README.md
=> creating README.md skeleton

.travis.yml, requirements.txt, requirements_pip.txt, spopt/region_k_means.py
=> cleaning up region_k_means.py

setup.py
=> Setup update

.github/workflows/unittests.yml
This PR sets up the `codecov` GitHub Action, addressing #24.
=> setting up codecov GitHub Action

README.md
This PR adds test, codecov, and license badges in `README.md`
=> test, codecov, and license badges in README

CONTRIBUTING.md
Initialize `spopt/.github/CONTRIBUTING.md` to address #35.
=> initialize CONTRIBUTING.md

setup.py
=> updating maintainer email

README.md
This PR adds a summarizing blurb to `README.md`
=> adding blurb to README

setup.py
This PR streamlines, and provides corrections for several rough edges in, `setup.py`.
=> Setup correction

.github/dependabot.yml
This PR adds `.github/dependabot.yml`.
=> adding .github/dependabot.yml

spopt/region/maxp.py
To fix error in maxp Line 220.
@rwei5 PTAL thanks!
=> change < to ==

README.md
=> removing python-mip language from REAMDE

.github/workflows/release_and_publish.yml, .github/workflows/unittests.yml
This PR:
* updates and streamlines `unittests.yml`
* add `release_and_publish.yml`
* this action is triggered by pushing a [tagged commit](https://git-scm.com/book/en/v2/Git-Basics-Tagging) ***directly*** to the `main` branch with the following pattern: `'v*'` i.e. `v2.0` or `v5.4.3`.
=> Update GitHub Actions

README.md, requirements_docs.txt
=> Adding support information.

README.md
=> add docs badge to README.md

spopt/__init__.py, tools/gitcount.ipynb
=> update changelog notebook

README.md, docs/index.rst, spopt/__init__.py
This PR address:
* #116 
* #115
=> Add Zenodo DOI and citation

README.md, docs/_static/pysal-styles.css, docs/_static/references.bib, docs/api.rst, docs/conf.py, docs/index.rst, docs/tutorials.rst
This PR provides minor updates to doc formatting, etc.
=> update docs & README

docs/_static/pysal-styles.css, environment.yml
This PR:
* addresses #126
* resolves [these comments](https://github.com/pysal/spopt/pull/125#discussion_r559046236)
=> Revert pysal-styles.ccs, etc.

.github/workflows/release_and_publish.yml, README.md
This PR attempts to address #128, #118, and conda-forge/staged-recipes#13708
=> add __token__ user to pypi step

setup.py, spopt/region/maxp.py
=> Include all packages.

requirements.txt, spopt/__init__.py
=> pulp to reqs

spopt/__init__.py
=> bump version 0.1.0 -> 0.1.1

README.md
=> update tutorials link in README

notebooks/randomregion.ipynb, spopt/region/__init__.py, spopt/region/components.py, spopt/region/random_region.py, spopt/tests/test_random_regions.py
=> Adding random regions

README.md, paper/paper.md
This PR
* corrects the indentation [mentioned in the review](https://github.com/openjournals/joss-reviews/issues/3303#issuecomment-846221678)
* adds the [JOSS submission badge](https://github.com/openjournals/joss-reviews/issues/3303) to `README.md`
=> correct paper indent & add JOSS badge

docs/notebooks/azp.ipynb, docs/notebooks/maxp.ipynb, docs/notebooks/reg-k-means.ipynb, docs/notebooks/ward.ipynb, notebooks/azp.ipynb, notebooks/maxp.ipynb, notebooks/ward.ipynb, paper/paper.md, spopt/region/azp.py, spopt/region/ward.py
=> Fixes documentation

.ci/37.yaml, .ci/38.yaml, .ci/39-DEV.yaml, .ci/39.yaml, .github/workflows/unittests.yml
=> maintenance for CI

.github/workflows/unittests.yml, .pre-commit-config.yaml, spopt/region/azp.py, spopt/region/azp_util.py, spopt/region/random_region.py, spopt/region/region_k_means.py, spopt/region/skater.py, spopt/region/spenc.py, spopt/region/spenclib/abstracts.py, spopt/region/spenclib/scores.py, spopt/region/spenclib/utils.py, spopt/region/util.py, spopt/region/ward.py, spopt/tests/test_azp.py, spopt/tests/test_maxp.py, spopt/tests/test_random_regions.py, spopt/tests/test_region_k_means.py, spopt/tests/test_region_util.py, spopt/tests/test_skater.py, spopt/tests/test_spenc.py, spopt/tests/test_ward.py
This PR begins to address #112.
* blackens repo
* Clean up (some) docstrings
* Streamlines tests by reusing objects
* Fills out testing suite
* basic AZP
* ~~simulated annealing AZP~~ **code needs attention**
* ~~Tabu AZP~~ **code needs attention**
* ~~basic tabu~~ **code needs attention**
* ~~reactive tabu~~  **code needs attention**
* `verbose == True`
* complex cases (e.g., check move and simulated annealing)
* one variable column for `attrs_name`
* random regions
* random region 
* reformatting and cleaning of test
* add complex lattice test
* test verbose
* fix and test super verbose
* add non-default parameters test
* test islands (pass & fail)
* defaults, gamma, n_clusters
* `spenc_lib`
* reformatting and cleaning of test
* test solver checks
=> Increase test cases & coverage

paper/paper.md
This PR adds an acknowledgment to the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/3330) that applies ***only to me*** with the following language:
> The following acknowledgement applies to James D. Gaboardi (affiliation 4) *only*:
>> This manuscript has been authored by UT-Battelle LLC under contract DE-AC05-00OR22725 with the US Department of Energy (DOE). The US government retains and the publisher, by accepting the article for publication, acknowledges that the US government retains a nonexclusive, paid-up, irrevocable worldwide license to publish or reproduce the published form of this manuscript, or allow others to do so, for US government purposes. DOE will provide public access to these results of federally sponsored research in accordance with the DOE …
=> Gaboardi/ORNL Acknowledgement

.pre-commit-config.yaml, docs/installation.rst
=> update pre-commit & bump supported python versions

.github/workflows/release_and_publish.yml
bump `actions/setup-python` from 2 to 3 in `release_and_publish.yml`.
=> bump actions/setup-python from 2 to 3

.github/workflows/build_docs.yml, .github/workflows/release_and_publish.yml, .github/workflows/unittests.yml
=> Bump actions/checkout from 2 to 3

paper/paper.bib, paper/paper.md
Address #248
xref openjournals/joss-reviews#3330
=> address reference concerns, etc. [2]

paper/paper.md
@gegen07 This PR cleans out the MCLP code block and adds in a couple sentences about the pre-existing facilities functionality.
=> clean out code block and add preexisting facility text

README.md, docs/index.rst
This PR adds the citation for the new [JOSS paper](https://joss.theoj.org/papers/10.21105/joss.03330) to the `README` and docs. We should also consider #255.
=> Update citation info

notebooks/lscp.ipynb
Added spaces in LSCP notebook problem formulation for readability.
=> Add spacing in lscp math definition

.gitignore
=> .coverage in .gitignore

README.md
Current first example doesn't work
=> Update regionalisation demo in README

.pre-commit-config.yaml, spopt/locate/coverage.py, spopt/locate/p_center.py, spopt/locate/p_dispersion.py, spopt/locate/p_median.py, spopt/region/skater.py, spopt/region/spenclib/utils.py
~~***EDIT*** On hold until more insight from https://github.com/pysal/momepy/pull/476.~~
This PR:
* follows up #359 with fixes for the fresh `ruff` failures.
* supersedes #361
=> address new `ruff` failures

spopt/locate/base.py, spopt/locate/coverage.py, spopt/locate/p_median.py
This adds a start for the capacitated p median model
=> [WIP] capacitated p median

docs/_static/references.bib
#380 
If the reference has any problem, please let me know!
=> add Church & Murray Business Site Selection to refs

.pre-commit-config.yaml
update precommit CI frequency -- resolve #392
=> update precommit CI frequency -- resolve #392

spopt/locate/p_median.py
This PR resolves #423.
xref #414
=> parameters & docstring clean up in `KNearestPMedian`

spopt/region/azp.py, spopt/region/util.py, spopt/tests/conftest.py, spopt/tests/test_azp.py, spopt/tests/test_c_p_median.py, spopt/tests/test_clscp-so.py, spopt/tests/test_locate_util.py, spopt/tests/test_lscp.py, spopt/tests/test_lscpb.py, spopt/tests/test_maxp.py, spopt/tests/test_mclp.py, spopt/tests/test_p_center.py, spopt/tests/test_p_dispersion.py, spopt/tests/test_p_median.py, spopt/tests/test_random_regions.py, spopt/tests/test_region_k_means.py, spopt/tests/test_skater.py, spopt/tests/test_spenc.py, spopt/tests/test_ward.py
xref #437 
This PR resolves some current warnings being thrown from within the codebase and in CI itself.
=> resolve some warnings in CI

README.md, docs/api.rst, docs/index.rst, docs/installation.rst
=> remove link to `gitter` room & add link to Discord channel

README.md
This PR adds [`OR_classic_problem`](https://github.com/khamechian1987/OR_classic_problem) to our `README` in the list of related projects.
=> add `OR_classic_problem` to README

spopt/region/maxp.py
=> fix `numpy=2.0.0` compat -- #456

.github/workflows/testing.yml
This PR:
* adds testing against intel & apple silicon - explicitly Intel or Apple - [see here](https://github.com/pysal/pysal/issues/1298#issuecomment-2106348049)
* xref https://github.com/pysal/pysal/issues/1298
=> explicit Mac intel test

.github/workflows/build_docs.yml, .github/workflows/testing.yml, ci/313-dev.yaml, ci/313-latest.yaml, environment.yml
=> add Python 3.13 to testing matrix

ci/311-oldest.yaml, environment.yml, pyproject.toml, spopt/region/sa3.py, spopt/tests/test_sa3.py
=> bump libpysal requirement to 4.10
