pysal/spopt

.github/workflows/unittests.yml

Address [this comment](https://github.com/pysal/spopt/pull/20#pullrequestreview-396055194).
Also, we are generating a `cov` report, but not actually checking/comparing/reporting anything from it. If we would like to set up `codecov`, I can do that easily, I will just need admin access to `spopt`.

streamlining GHA testing

---

.github/workflows/unittests.yml
ci/38.yaml
setup.py

This PR:
*  add testing for Python 3.8 in the unittest workflow
* update setup for supported Python versions

Add testing for Python 3.8

---

codecov.yml

This PR adds a customized `codecov.yml` that:
* allows for a 2% change threshold without failing
* decreases precision to 1 decimal place
* assigns 95% coverage as "complete"
* waits until all 9 builds are complete before commenting here

adding customized codecov.yml

---

spopt/__init__.py
spopt/region/__init__.py
spopt/region/ward.py
spopt/tests/test_ward.py

move ward function from geosnap to spopt.

add ward and test_ward

---

README.md
codecov.yml
setup.py

In order to provide a more inclusive environment and address problematic language we should update the `master` branch to `main`. 
See #68, pysal/spaghetti#543, pysal/libpysal#353

Updating links from `master` branch to `main` branch

---

.ci/37.yaml
.ci/38.yaml
.ci/39.yaml
environment.yml
requirements.txt
requirements_docs.txt
spopt/BaseClass.py
spopt/__init__.py

there's been some movement on the ortools package for conda-forge but its not available yet. Thus, while ortools is a hard dependency, we can't release spopt on conda-forge. This temporarily removes it as a dep and we can add it back once things are sorted

remove ortools

---

.github/workflows/build_docs.yml
setup.py
spopt/__init__.py

This PR bumps the initial release version down to `v0.0.1` in order to:
* troubleshoot any issues with the release GHA (#116)
* generate a zenodo DOI (#115)

bump initial version down to 0.0.1

---

spopt/__init__.py

This PR simply increments the version up to `0.0.2` following a manual release of `v0.0.1` on PyPI. This manual release was done prior to a GitHub release of `v0.0.1` in order to facilitate the testing of the automated release+publish workflow.

bump version to v0.0.2

---

README.md

This PR updates the broken/old link to the developer documentation. This change should be made in `README`s across the ecosystem. See the `rst` fix in [`libpysal `](https://github.com/pysal/libpysal/commit/5cf5f0f59f74e88d9cec887aca564ad4527c8593).

update dev docs link

---

.gitattributes

This PR classifies the `spopt` repo as being 100% (ignores html, tex, etc.) for GitHub searches.

Classify repo as Python

---

.github/workflows/build_docs.yml
.github/workflows/unittests.yml
notebooks/reg-k-means.ipynb

This PR:
* adds a manual trigger to the `doc_build.yml` action
* swaps out `conda` for `micromamba` in setting up Python
* minor correction in `reg-k-means.ipynb`
* minor correction in `unittests.yml`

add trigger to doc_build action

---

docs/conf.py

Link at the top on Tutorial pages to the notebooks seem to be broken. This PR attempts a fix.

update notebook links in conf

---

docs/_static/pysal-styles.css
docs/_static/references.bib
docs/index.rst

1st attempt at cleaning up https://pysal.org/spopt/

Doc site work

---

README.md
docs/api.rst
requirements.txt
spopt/locate/base.py
spopt/locate/coverage.py
spopt/locate/p_center.py
spopt/locate/p_median.py
spopt/locate/util.py

Add examples section to locate module

---

tools/gitcount.ipynb

xref pysal/spaghetti#654, pysal/libpysal#434
In order to take advantage of using [`tools/gitcount.ipynb`](https://github.com/pysal/spopt/blob/master/tools/gitcount.ipynb) with the newly adopted `versioneer`schema, the version import cell must be split into two cells and changed from:
```python
f = "../{package}/__init__.py".format(package=package_name)
with open(f, "r") as initfile:
exec(initfile.readline())
```
to:
```python
%run ../spopt/_version.py
```
```python
__version__ = get_versions()["version"]
```

access package version in tools/gitcount

---

.github/workflows/build_docs.yml

Seems that we need to install pulp for docs build. See failure [here](https://github.com/pysal/spopt/runs/4087183779?check_suite_focus=true).

install pulp for docs build

---

.ci/310-DEV.yaml
.ci/310.yaml
.github/workflows/unittests.yml
codecov.yml
setup.py
spopt/region/util.py

The PR adds Python 3.10 to the GHA testing schema.

add 310 to CI matrix

---

.ci/310-DEV.yaml
.ci/310.yaml
.ci/37.yaml
.ci/38.yaml
.ci/39.yaml
.github/workflows/unittests.yml
requirements_tests.txt

This PR allows for multiprocessing in through `pytest`, which decreases runtime.
xref: pysal/spaghetti#661

Xdist tests

---

spopt/region/azp_util.py
spopt/region/maxp.py
spopt/region/region_k_means.py

Partially address #173.
Doesn't touch skater.

Region docs

---

paper/paper.md

This PR update the footnote hyperlinks in the JOSS manuscript.
xref - openjournals/joss-reviews#3330

JOSS -- update footnote hyperlinks

---

spopt/tests/test_region_k_means.py

This PR provides a temporary solution to #213 until we figure out what to do more permanently.

mark k_means_heuristic_synth_small test with xfail 

---

.coveragerc
spopt/BaseClass.py
spopt/locate/base.py
spopt/locate/coverage.py
spopt/locate/p_center.py
spopt/locate/p_dispersion.py
spopt/locate/p_median.py
spopt/region/azp.py
spopt/region/base.py
spopt/region/components.py
spopt/region/csgraph_utils.py
spopt/region/maxp.py
spopt/region/objective_function.py
spopt/region/random_region.py
spopt/region/region_k_means.py
spopt/region/spenc.py
spopt/region/util.py
spopt/tests/test_azp.py
spopt/tests/test_locate.py
spopt/tests/test_lscpb.py
spopt/tests/test_maxp.py
spopt/tests/test_p_dispersion.py
spopt/tests/test_random_regions.py
spopt/tests/test_region_k_means.py
spopt/tests/test_region_util.py
spopt/tests/test_skater.py
spopt/tests/test_spenc.py
spopt/tests/test_ward.py

This PR:
* `black` formats repo (because somehow that never happened?)
* resolves nearly all warnings deprecation warnings in CI
* see geopandas/geopandas#2596
* converts testing infrastructure from `unittest` to `pytest`
* adds matching for specific warnings & errors and thrown messages from *all*  that are currently tested against.
* other minor streamlines

testing overhaul, etc

---

spopt/BaseClass.py
spopt/locate/base.py

This PR removes the `ortools` import in `BaseClass` so that `BaseSpOptExactSolver` can then be inherited by `LocateSolver` instances.
xref #298 #49

utilize `BaseSpOptExactSolver`

---

spopt/region/base.py
spopt/region/random_region.py
spopt/region/util.py
spopt/region/ward.py
spopt/tests/test_random_regions.py

This PR continues pushing towards a completion of #173 --> #280 and covers:
* `random_region.py`
* `util.py`
* `ward.py`

doc work and formatting continued (random_region, util, ward)

---

.ci/310-DEV.yaml
.ci/310-DEV_shapely_dev.yaml
.ci/310.yaml
.ci/38.yaml
.ci/39.yaml
docs/_static/references.bib
spopt/region/spenc.py
spopt/region/spenclib/abstracts.py

This PR
* resolves #172 
* resolves #310

expose SPENC kwargs

---

spopt/locate/base.py
spopt/locate/coverage.py
spopt/locate/p_center.py
spopt/locate/p_dispersion.py
spopt/locate/p_median.py
spopt/tests/test_locate.py
spopt/tests/test_lscpb.py
spopt/tests/test_p_dispersion.py

This PR resolves #317; there is no change to actual functionality.

Streamline redundant parameter passing in constraint constructors

---

.ci/310.yaml
.ci/311.yaml

This PR removes the [`.ci/311.yml`](https://github.com/pysal/spopt/blob/main/.ci/311.yaml) `sphinx` version pin that I forgot to remove in #309 and also removes the doc building packages from [`.ci/310.yml`](https://github.com/pysal/spopt/blob/main/.ci/310.yaml) since we will be building documentation with the `.ci/311.yml` environment.

doc build env correction

---

notebooks/lscp_capacity.ipynb
spopt/locate/base.py
spopt/locate/coverage.py
spopt/locate/p_center.py
spopt/locate/p_median.py

This PR resolves #328. Following merge we can cut release `v0.5.0` 🎉 
xref #331

[BUG] bounds for client assignment variables

---

.github/workflows/versioneer.yml
setup.py

This PR resolves #339.
Adapted from [`spaghetti`](https://github.com/pysal/spaghetti/blob/main/.github/workflows/versioneer.yml)'s version because we haven't adopted `pyproject.toml` here yet (#325) (specifically `{"build_py": build_py}` needs to be removed [here](https://github.com/pysal/spopt/blob/f2ac58f806737e82726ef34ac36c253ea7e0ca56/setup.py#L39)).
* passing --> https://github.com/jGaboardi/spopt/actions/runs/3907911521/jobs/6677596851

add versioneer action

---

MANIFEST.in

This PR resolves #343.
xref https://github.com/conda-forge/spopt-feedstock/pull/12#issuecomment-1382356827

Add `requirements_notebooks.txt` to MANIFEST

---

.pre-commit-config.yaml
docs/api.rst
spopt/locate/__init__.py
spopt/locate/p_median.py

Add `KNearestPMP` to API and documentation. Follows up #397.

Add KNearestPMP to API and documentation

---

spopt/locate/coverage.py

Bug #410 means that no capacitated LSCP will ever be solvable through `from_geodataframe()`. The check requires that demand weight is less than capacity, but transposes the capacity and demand arrays. So, all cases where capacity is greater than demand have an error raised saying that there is not enough capacity, while all cases where capacity is *less than* demand proceed to solve and return infeasible. 
This fixes the transposition.

solve b410

---

pyproject.toml
spopt/BaseClass.py
spopt/locate/base.py
spopt/locate/coverage.py
spopt/locate/p_center.py
spopt/locate/p_dispersion.py
spopt/locate/p_median.py
spopt/locate/util.py
spopt/region/azp.py
spopt/region/azp_util.py
spopt/region/base.py
spopt/region/maxp.py
spopt/region/random_region.py
spopt/region/region_k_means.py
spopt/region/skater.py
spopt/region/spenc.py
spopt/region/spenclib/abstracts.py
spopt/region/spenclib/scores.py
spopt/region/spenclib/utils.py
spopt/region/ward.py

* Stricter linting – follow up #413
* This touches more lines of code than I thought it would... As usual, I can split if desired.

stricter linting – follow up #413

---

spopt/locate/coverage.py
spopt/locate/p_dispersion.py
spopt/locate/p_median.py

This PR resolves #421.
xref #414

`locate` models – standardized default names

---

spopt/tests/test_knearest_p_median.py

This PR partially addresses #427, except for the two I created another issue for – #428.

flesh out `kn-pmp` testing

---

spopt/locate/base.py
spopt/locate/p_median.py

Formulation of KN-PMP omitted opening constraints 

---

spopt/locate/p_median.py
spopt/tests/test_knearest_p_median.py

This MR:
* resolves #425 
* does some more docstring clean up
xref #414

Review messaging in KN-PMP

---

docs/_static/references.bib
spopt/locate/p_median.py

This PR resolves [this comment](https://github.com/pysal/spopt/pull/426#pullrequestreview-1774053744).

fix Church 2018 (tobler paper) cite

---

.gitattributes
.github/CONTRIBUTING.md
.pre-commit-config.yaml
README.md
pyproject.toml
spopt/region/azp_util.py

Switch repository formatting to `ruff`

---

.github/workflows/testing.yml

This PR adds a specific Apple Silicon environment to the CI matrix:
* xref https://github.com/pysal/momepy/pull/542/
* [GitHub Blog](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)

test against Apple silicon

---

.pre-commit-config.yaml
docs/conf.py
pyproject.toml
spopt/region/components.py
spopt/region/csgraph_utils.py
spopt/tests/conftest.py
spopt/tests/test_azp.py
spopt/tests/test_c_p_median.py
spopt/tests/test_clscp-so.py
spopt/tests/test_knearest_p_median.py
spopt/tests/test_locate_util.py
spopt/tests/test_lscp.py
spopt/tests/test_lscpb.py
spopt/tests/test_maxp.py
spopt/tests/test_mclp.py
spopt/tests/test_p_center.py
spopt/tests/test_p_dispersion.py
spopt/tests/test_p_median.py
spopt/tests/test_random_regions.py
spopt/tests/test_region_k_means.py
spopt/tests/test_region_util.py
spopt/tests/test_skater.py
spopt/tests/test_spenc.py
spopt/tests/test_ward.py

This PR:
* resolves #438 
* re-lints & re-formats with latest `ruff`
* extends linting & formatting to the `tests/*` directory.

re- lint & re-format repo – #438

---

.github/workflows/testing.yml
.pre-commit-config.yaml
spopt/locate/util.py
spopt/tests/conftest.py
spopt/tests/test_c_p_median.py
spopt/tests/test_clscp-so.py
spopt/tests/test_knearest_p_median.py
spopt/tests/test_lscp.py
spopt/tests/test_lscpb.py
spopt/tests/test_mclp.py
spopt/tests/test_p_center.py
spopt/tests/test_p_dispersion.py
spopt/tests/test_p_median.py
spopt/tests/test_skater.py

This PR:
* resolves #448 
* resolves #450 
* resolves #451 
* resolves #452
* eliminated CI warnings in all by `oldest` and `dev`

testing code cleanup

---

.pre-commit-config.yaml
spopt/region/components.py
spopt/region/spenclib/abstracts.py
spopt/region/spenclib/utils.py
spopt/region/util.py
spopt/tests/conftest.py
spopt/tests/test_c_p_median.py

bump `ruff` version in precommit

bump `ruff` version in precommit

---

spopt/region/csgraph_utils.py

This small PR resolves the NumPy deprecation warnings of `np.in1d`:
```python
/home/runner/work/spopt/spopt/spopt/region/csgraph_utils.py:142: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
```

Update numpy array comparisons to use isin
